export type Mode = "image" | "video";
export type Progress = { value: number; max: number; node?: string };
export type Output = { url: string; filename: string; type: "image" | "video"; prompt?: string; negative?: string; outputName?: string };
export type LoraSelection = { name: string; enabled: boolean; strength: number };
export type MediaInput = {
  id: string;
  kind: "image";
  required?: boolean;
  min?: number;
  max?: number;
  label?: string;
  control?: { node: string; input: string };
};
export type ReferenceAsset = {
  id: string;
  source: "upload" | "generation" | "vault";
  name: string;
  mime: string;
  width: number;
  height: number;
  size: number;
  createdAt: string;
  thumbnailUrl: string;
  url?: string;
  privacyDomain?: "gallery" | "vault";
  galleryItemId?: string;
};
export type SelectedReferenceAsset = { slot: string; asset: ReferenceAsset };
export type PromptComposition = { prefix?: string; suffix?: string; policy?: string; version?: number };
export type GenerationSettings = Record<string, string | number | boolean | null | undefined | LoraSelection[]>;
export type UpscaleQuality = "fast" | "balanced" | "high";
export type UpscaleState = {
  status: "running" | "done" | "error" | "canceled";
  jobId?: string;
  quality?: UpscaleQuality;
  faceDetail?: boolean;
  progress?: Progress | null;
  url?: string;
  thumbnailUrl?: string;
  outputName?: string;
  width?: number;
  height?: number;
  scale?: number;
  error?: string;
  startedAt?: string;
  completedAt?: string;
};
export type GalleryItem = Output & { id: string; jobId?: string; status: "done" | "pending" | "error" | "canceled"; progress?: Progress; preview?: string; width?: number; height?: number; createdAt?: string; durationMs?: number; model?: string; settings?: GenerationSettings; index?: number; referenceImage?: string; referenceImageName?: string; startImageId?: string; optimistic?: boolean; promptProtected?: boolean; privateVault?: boolean; vaultLocked?: boolean; thumbnailUrl?: string; upscale?: UpscaleState; upscaleActive?: boolean; bundle?: GalleryBundle };
export type GalleryBundle = {
  id: string;
  domain: "gallery" | "vault";
  reason: "prompt" | "batch";
  reasonLabel: string;
  count: number;
  startedAt: string;
  endedAt: string;
  coverId: string;
  items: GalleryItem[];
};
export type BundlePending = { runs: number; items: number; itemIds?: string[] };
export type BundleStatus = { bundles: unknown[]; pending: BundlePending; mode: string; cooldownMinutes: number };
export type Job = { status: string; outputs: GalleryItem[]; error?: string; progress?: Progress; preview?: string; previews?: string[] };
export type TouchGesture = { mode: "pan"; id: number; x: number; y: number; panX: number; panY: number; moved: boolean } | { mode: "pinch"; distance: number; zoom: number; panX: number; panY: number; centerX: number; centerY: number; moved: boolean };
export type SelectOption = { label: string; value: string };
export type Profile = {
  id: string;
  kind: Mode;
  label: string;
  displayName?: string;
  description?: string;
  model: string;
  workflow: string;
  family: string;
  defaults: Record<string, string | number>;
  aspectPresets: AspectPreset[];
  constraints?: Record<string, { min?: number; max?: number; step?: number; default?: number }>;
  options?: {
    textEncoders?: string[];
    vaes?: string[];
    clipTypes?: string[];
    weightDtypes?: string[];
    samplers?: string[];
    schedulers?: string[];
    loras?: string[];
  };
  capabilities: Record<string, boolean>;
  mediaInputs?: MediaInput[];
  aspectPolicy?: "manual" | "reference";
};
export type Models = {
  imageModels: SelectOption[];
  videoModels: SelectOption[];
  profiles: Profile[];
  unsupportedModels?: string[];
  textEncoders: string[];
  vaes: string[];
  clipTypes?: string[];
  weightDtypes?: string[];
  samplers: string[];
  schedulers: string[];
  loras?: string[];
  defaults: Record<string, string>;
  capabilities: Record<string, boolean>;
};
export type Paths = { outputDir?: string; galleryDir?: string; workflowsDir?: string };
export type Health = { ok: boolean; comfyUrl?: string; error?: string };
export type ComfyStatus = { connected: boolean; url?: string; latencyMs?: number; version?: string; device?: string; error?: string; checking?: boolean };
export type UpdateStatus = { ok: boolean; available?: boolean; current?: string; latest?: string; branch?: string; behind?: number; updated?: boolean; restartRequired?: boolean; message?: string; error?: string };
export type AspectPreset = { label: string; value: string; w: number; h: number };
export type WorkflowValidation = { ok: boolean; issues: string[]; warnings?: string[]; missingNodes?: string[] };
export type WorkflowSummary = {
  id: string;
  profileId: string;
  workflow: string;
  name: string;
  description?: string;
  kind: Mode;
  family: string;
  source: "builtin" | "custom";
  deleteId?: string;
  controls?: string[];
  capabilities?: Record<string, boolean>;
  mediaInputs?: MediaInput[];
  aspectPolicy?: "manual" | "reference";
  defaults?: Record<string, string | number | boolean | null | undefined>;
  path?: string;
  favorite?: boolean;
  lastUsedAt?: string;
  thumbnail?: string;
  tags?: string[];
  validation: WorkflowValidation;
};
export type WorkflowPreferences = { favorites: string[]; lastUsed: Record<string, string>; thumbnails: Record<string, string> };
export type WorkflowImportPreview = {
  filename?: string;
  format?: string;
  hasJaiStudio: boolean;
  detected: {
    id: string;
    name: string;
    description?: string;
    kind: Mode;
    family: string;
    controls: Record<string, { node: string; input: string }>;
    defaults?: Record<string, unknown>;
    capabilities?: Record<string, boolean>;
    mediaInputs?: MediaInput[];
    promptComposition?: PromptComposition | null;
    aspectRatios?: unknown[];
    aspectPolicy?: "manual" | "reference";
    nodes: Array<{ id: string; classType: string; inputs: string[]; suggestedInputs: string[] }>;
  };
  validation: WorkflowValidation;
};

export type Preferences = {
  defaultImageCount: number;
  defaultImageSteps: number;
  defaultVideoFrames: number;
  defaultVideoSteps: number;
  defaultFps: number;
  generationPreviewMode: "advanced" | "simple";
  variationQueueMode: "batch" | "separate";
  zenMode: boolean;
  confirmActions: boolean;
  enterToGenerate: boolean;
  followLatest: boolean;
  showFailedItems: boolean;
  groupRuns: boolean;
  runGroupingMode: "smart" | "job";
  runCooldownMinutes: number;
  smartUpscale: boolean;
  upscaleQuality: UpscaleQuality;
  upscaleFaceDetail: boolean;
  mobileZenDefaulted?: boolean;
};

export type UpscaleModelInfo = { key: string; file: string; label: string; approxBytes: number; present: boolean };
export type UpscaleInstall = {
  status: "running" | "done" | "error" | "canceled";
  dir?: string;
  current?: string;
  files?: Array<{ file: string; label: string; bytes: number; totalBytes: number; done: boolean }>;
  receivedBytes?: number;
  totalBytes?: number;
  error?: string;
  restartHint?: boolean;
} | null;
export type UpscaleStatus = {
  ok?: boolean;
  quality: UpscaleQuality;
  nodesInstalled: boolean;
  missingNodes: string[];
  detectedNodes?: string[];
  modelDir: string;
  canDownload: boolean;
  models: UpscaleModelInfo[];
  missingModels: string[];
  needsDownload: boolean;
  substituting: boolean;
  ready: boolean;
  faceDetail: { nodesInstalled: boolean; missingNodes: string[]; detectors: string[]; samModels: string[] };
  install: UpscaleInstall;
};
export type UpscaleDownloadPreview = { quality: UpscaleQuality; modelDir: string; totalBytes: number; files: Array<{ key: string; file: string; label: string; bytes: number; exact: boolean }> };

export type PrivacyStatus = { enabled: boolean; unlocked: boolean; cookieName?: string; vault?: { enabled: boolean; unlocked: boolean; assetCount: number } };
